// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Departamento.sql

package repository

import (
	"context"
)

const buscarDepartamento = `-- name: BuscarDepartamento :one
SELECT id, nome 
FROM departamento 
WHERE id = $1 AND ativo = TRUE 
LIMIT 1
`

type BuscarDepartamentoRow struct {
	ID   int32
	Nome string
}

func (q *Queries) BuscarDepartamento(ctx context.Context, id int32) (BuscarDepartamentoRow, error) {
	row := q.db.QueryRow(ctx, buscarDepartamento, id)
	var i BuscarDepartamentoRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const buscarTodosDepartamentos = `-- name: BuscarTodosDepartamentos :many
SELECT id, nome 
FROM departamento 
WHERE ativo = TRUE
`

type BuscarTodosDepartamentosRow struct {
	ID   int32
	Nome string
}

func (q *Queries) BuscarTodosDepartamentos(ctx context.Context) ([]BuscarTodosDepartamentosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosDepartamentos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosDepartamentosRow
	for rows.Next() {
		var i BuscarTodosDepartamentosRow
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criaDepartamento = `-- name: CriaDepartamento :exec
insert into departamento (nome) 
values ($1)
`

func (q *Queries) CriaDepartamento(ctx context.Context, nome string) error {
	_, err := q.db.Exec(ctx, criaDepartamento, nome)
	return err
}

const deletarDepartamento = `-- name: DeletarDepartamento :execrows
UPDATE departamento
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarDepartamento(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarDepartamento, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartamento = `-- name: UpdateDepartamento :execrows
UPDATE departamento
SET nome = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateDepartamentoParams struct {
	ID   int32
	Nome string
}

func (q *Queries) UpdateDepartamento(ctx context.Context, arg UpdateDepartamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDepartamento, arg.ID, arg.Nome)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
