// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Epi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEpi = `-- name: AddEpi :one
INSERT INTO epi (nome, fabricante, CA, descricao, validade_CA, IdTipoProtecao, alerta_minimo) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type AddEpiParams struct {
	Nome           string
	Fabricante     string
	Ca             string
	Descricao      string
	ValidadeCa     pgtype.Date
	Idtipoprotecao int32
	AlertaMinimo   int32
}

func (q *Queries) AddEpi(ctx context.Context, arg AddEpiParams) (int32, error) {
	row := q.db.QueryRow(ctx, addEpi,
		arg.Nome,
		arg.Fabricante,
		arg.Ca,
		arg.Descricao,
		arg.ValidadeCa,
		arg.Idtipoprotecao,
		arg.AlertaMinimo,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const addEpiTamanho = `-- name: AddEpiTamanho :exec
INSERT INTO tamanhos_epis (IdEpi, IdTamanho) 
VALUES ($1, $2)
`

type AddEpiTamanhoParams struct {
	Idepi     int32
	Idtamanho int32
}

func (q *Queries) AddEpiTamanho(ctx context.Context, arg AddEpiTamanhoParams) error {
	_, err := q.db.Exec(ctx, addEpiTamanho, arg.Idepi, arg.Idtamanho)
	return err
}

const buscarEpi = `-- name: BuscarEpi :one
SELECT 
    e.id, e.nome, e.fabricante, e.CA, e.descricao,
    e.validade_CA, e.alerta_minimo, e.IdTipoProtecao, 
    tp.nome as tipo_protecao_nome
FROM epi e
INNER JOIN tipo_protecao tp ON e.IdTipoProtecao = tp.id
WHERE e.id = $1 AND e.ativo = TRUE
`

type BuscarEpiRow struct {
	ID               int32
	Nome             string
	Fabricante       string
	Ca               string
	Descricao        string
	ValidadeCa       pgtype.Date
	AlertaMinimo     int32
	Idtipoprotecao   int32
	TipoProtecaoNome string
}

func (q *Queries) BuscarEpi(ctx context.Context, id int32) (BuscarEpiRow, error) {
	row := q.db.QueryRow(ctx, buscarEpi, id)
	var i BuscarEpiRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Fabricante,
		&i.Ca,
		&i.Descricao,
		&i.ValidadeCa,
		&i.AlertaMinimo,
		&i.Idtipoprotecao,
		&i.TipoProtecaoNome,
	)
	return i, err
}

const buscarTamanhosPorEpi = `-- name: BuscarTamanhosPorEpi :many
SELECT t.id, t.tamanho
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.IdEpi = $1 AND te.ativo = TRUE
`

type BuscarTamanhosPorEpiRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTamanhosPorEpi(ctx context.Context, idepi int32) ([]BuscarTamanhosPorEpiRow, error) {
	rows, err := q.db.Query(ctx, buscarTamanhosPorEpi, idepi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTamanhosPorEpiRow
	for rows.Next() {
		var i BuscarTamanhosPorEpiRow
		if err := rows.Scan(&i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosEpisPaginado = `-- name: BuscarTodosEpisPaginado :many
SELECT 
    e.id, e.nome, e.fabricante, e.CA, e.descricao,
    e.validade_CA, e.alerta_minimo, e.IdTipoProtecao, 
    tp.nome as tipo_protecao_nome,
    COUNT(*) OVER() as total_geral
FROM epi e
INNER JOIN tipo_protecao tp ON e.IdTipoProtecao = tp.id
WHERE e.ativo = TRUE
order by e.id
LIMIT $1 OFFSET $2
`

type BuscarTodosEpisPaginadoParams struct {
	Limit  int32
	Offset int32
}

type BuscarTodosEpisPaginadoRow struct {
	ID               int32
	Nome             string
	Fabricante       string
	Ca               string
	Descricao        string
	ValidadeCa       pgtype.Date
	AlertaMinimo     int32
	Idtipoprotecao   int32
	TipoProtecaoNome string
	TotalGeral       int64
}

func (q *Queries) BuscarTodosEpisPaginado(ctx context.Context, arg BuscarTodosEpisPaginadoParams) ([]BuscarTodosEpisPaginadoRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosEpisPaginado, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosEpisPaginadoRow
	for rows.Next() {
		var i BuscarTodosEpisPaginadoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Fabricante,
			&i.Ca,
			&i.Descricao,
			&i.ValidadeCa,
			&i.AlertaMinimo,
			&i.Idtipoprotecao,
			&i.TipoProtecaoNome,
			&i.TotalGeral,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosTamanhosAgrupados = `-- name: BuscarTodosTamanhosAgrupados :many
SELECT te.IdEpi, t.id, t.tamanho
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.ativo = TRUE
`

type BuscarTodosTamanhosAgrupadosRow struct {
	Idepi   int32
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTodosTamanhosAgrupados(ctx context.Context) ([]BuscarTodosTamanhosAgrupadosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosTamanhosAgrupados)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosTamanhosAgrupadosRow
	for rows.Next() {
		var i BuscarTodosTamanhosAgrupadosRow
		if err := rows.Scan(&i.Idepi, &i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarEpi = `-- name: DeletarEpi :execrows
UPDATE epi SET ativo = FALSE, deletado_em = NOW() WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarEpi(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarEpi, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletarTamanhosPorEpi = `-- name: DeletarTamanhosPorEpi :execrows
UPDATE tamanhos_epis SET ativo = FALSE, deletado_em = NOW() WHERE IdEpi = $1 AND ativo = TRUE
`

func (q *Queries) DeletarTamanhosPorEpi(ctx context.Context, idepi int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarTamanhosPorEpi, idepi)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpiCampo = `-- name: UpdateEpiCampo :execrows
UPDATE epi 
SET id = COALESCE($1, id),
    nome = COALESCE($2, nome),
    fabricante = COALESCE($3, fabricante),
    CA = COALESCE($4, CA),
    descricao = COALESCE($5, descricao),
    validade_CA = COALESCE($6, validade_CA)
WHERE id = $1 AND ativo = TRUE
`

type UpdateEpiCampoParams struct {
	ID         pgtype.Int4
	Nome       pgtype.Text
	Fabricante pgtype.Text
	Ca         pgtype.Text
	Descricao  pgtype.Text
	ValidadeCa pgtype.Date
}

func (q *Queries) UpdateEpiCampo(ctx context.Context, arg UpdateEpiCampoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEpiCampo,
		arg.ID,
		arg.Nome,
		arg.Fabricante,
		arg.Ca,
		arg.Descricao,
		arg.ValidadeCa,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
