// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Funcao.sql

package repository

import (
	"context"
)

const addFuncao = `-- name: AddFuncao :exec
INSERT INTO funcao (nome, IdDepartamento) 
VALUES ($1, $2)
`

type AddFuncaoParams struct {
	Nome           string
	Iddepartamento int32
}

func (q *Queries) AddFuncao(ctx context.Context, arg AddFuncaoParams) error {
	_, err := q.db.Exec(ctx, addFuncao, arg.Nome, arg.Iddepartamento)
	return err
}

const buscarFuncao = `-- name: BuscarFuncao :one
SELECT 
    f.id, 
    f.nome, 
    f.IdDepartamento, 
    d.nome as departamento_nome
FROM funcao f
INNER JOIN departamento d ON f.IdDepartamento = d.id
WHERE f.id = $1 AND f.ativo = TRUE
`

type BuscarFuncaoRow struct {
	ID               int32
	Nome             string
	Iddepartamento   int32
	DepartamentoNome string
}

func (q *Queries) BuscarFuncao(ctx context.Context, id int32) (BuscarFuncaoRow, error) {
	row := q.db.QueryRow(ctx, buscarFuncao, id)
	var i BuscarFuncaoRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Iddepartamento,
		&i.DepartamentoNome,
	)
	return i, err
}

const buscarTodasFuncoes = `-- name: BuscarTodasFuncoes :many
SELECT 
    f.id, 
    f.nome, 
    f.IdDepartamento, 
    d.nome as departamento_nome
FROM funcao f
INNER JOIN departamento d ON f.IdDepartamento = d.id
WHERE f.ativo = TRUE
`

type BuscarTodasFuncoesRow struct {
	ID               int32
	Nome             string
	Iddepartamento   int32
	DepartamentoNome string
}

func (q *Queries) BuscarTodasFuncoes(ctx context.Context) ([]BuscarTodasFuncoesRow, error) {
	rows, err := q.db.Query(ctx, buscarTodasFuncoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodasFuncoesRow
	for rows.Next() {
		var i BuscarTodasFuncoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Iddepartamento,
			&i.DepartamentoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarFuncao = `-- name: DeletarFuncao :execrows
UPDATE funcao
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarFuncao(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarFuncao, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const possuiFuncionariosVinculados = `-- name: PossuiFuncionariosVinculados :one
SELECT EXISTS (
    SELECT 1 FROM funcionario 
    WHERE IdFuncao = $1 AND ativo = TRUE
)
`

func (q *Queries) PossuiFuncionariosVinculados(ctx context.Context, idfuncao int32) (bool, error) {
	row := q.db.QueryRow(ctx, possuiFuncionariosVinculados, idfuncao)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateFuncao = `-- name: UpdateFuncao :execrows
UPDATE funcao
SET nome = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateFuncaoParams struct {
	ID   int32
	Nome string
}

func (q *Queries) UpdateFuncao(ctx context.Context, arg UpdateFuncaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncao, arg.ID, arg.Nome)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
