// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Funcionarios.sql

package repository

import (
	"context"
)

const addFuncionario = `-- name: AddFuncionario :exec
INSERT INTO funcionario (nome, matricula, IdDepartamento, IdFuncao) 
VALUES ($1, $2, $3, $4)
`

type AddFuncionarioParams struct {
	Nome           string
	Matricula      string
	Iddepartamento int32
	Idfuncao       int32
}

func (q *Queries) AddFuncionario(ctx context.Context, arg AddFuncionarioParams) error {
	_, err := q.db.Exec(ctx, addFuncionario,
		arg.Nome,
		arg.Matricula,
		arg.Iddepartamento,
		arg.Idfuncao,
	)
	return err
}

const buscaFuncionario = `-- name: BuscaFuncionario :one
SELECT 
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.matricula = $1 AND fn.ativo = TRUE
`

type BuscaFuncionarioRow struct {
	ID               int32
	Nome             string
	Matricula        string
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
}

func (q *Queries) BuscaFuncionario(ctx context.Context, matricula string) (BuscaFuncionarioRow, error) {
	row := q.db.QueryRow(ctx, buscaFuncionario, matricula)
	var i BuscaFuncionarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Matricula,
		&i.Iddepartamento,
		&i.DepartamentoNome,
		&i.Idfuncao,
		&i.FuncaoNome,
	)
	return i, err
}

const buscaFuncionarioPorId = `-- name: BuscaFuncionarioPorId :one
SELECT 
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.id = $1 AND fn.ativo = TRUE
`

type BuscaFuncionarioPorIdRow struct {
	ID               int32
	Nome             string
	Matricula        string
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
}

func (q *Queries) BuscaFuncionarioPorId(ctx context.Context, id int32) (BuscaFuncionarioPorIdRow, error) {
	row := q.db.QueryRow(ctx, buscaFuncionarioPorId, id)
	var i BuscaFuncionarioPorIdRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Matricula,
		&i.Iddepartamento,
		&i.DepartamentoNome,
		&i.Idfuncao,
		&i.FuncaoNome,
	)
	return i, err
}

const buscarTodosFuncionarios = `-- name: BuscarTodosFuncionarios :many
SELECT 
    fn.id, 
    fn.nome, 
    fn.matricula, 
    fn.IdDepartamento, 
    d.nome as departamento_nome,
    fn.IdFuncao, 
    f.nome as funcao_nome
FROM funcionario fn
INNER JOIN departamento d ON fn.IdDepartamento = d.id
INNER JOIN funcao f ON fn.IdFuncao = f.id
WHERE fn.ativo = TRUE
`

type BuscarTodosFuncionariosRow struct {
	ID               int32
	Nome             string
	Matricula        string
	Iddepartamento   int32
	DepartamentoNome string
	Idfuncao         int32
	FuncaoNome       string
}

func (q *Queries) BuscarTodosFuncionarios(ctx context.Context) ([]BuscarTodosFuncionariosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosFuncionarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosFuncionariosRow
	for rows.Next() {
		var i BuscarTodosFuncionariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Matricula,
			&i.Iddepartamento,
			&i.DepartamentoNome,
			&i.Idfuncao,
			&i.FuncaoNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarFuncionario = `-- name: DeletarFuncionario :execrows
UPDATE funcionario
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarFuncionario(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarFuncionario, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioDepartamento = `-- name: UpdateFuncionarioDepartamento :execrows
UPDATE funcionario
SET IdDepartamento = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateFuncionarioDepartamentoParams struct {
	ID             int32
	Iddepartamento int32
}

func (q *Queries) UpdateFuncionarioDepartamento(ctx context.Context, arg UpdateFuncionarioDepartamentoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioDepartamento, arg.ID, arg.Iddepartamento)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioFuncao = `-- name: UpdateFuncionarioFuncao :execrows
UPDATE funcionario
SET IdFuncao = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateFuncionarioFuncaoParams struct {
	ID       int32
	Idfuncao int32
}

func (q *Queries) UpdateFuncionarioFuncao(ctx context.Context, arg UpdateFuncionarioFuncaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioFuncao, arg.ID, arg.Idfuncao)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFuncionarioNome = `-- name: UpdateFuncionarioNome :execrows
UPDATE funcionario
SET nome = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateFuncionarioNomeParams struct {
	ID   int32
	Nome string
}

func (q *Queries) UpdateFuncionarioNome(ctx context.Context, arg UpdateFuncionarioNomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuncionarioNome, arg.ID, arg.Nome)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
