// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: MotivoDevolucao.sql

package repository

import (
	"context"
)

const addMotivoDevolucao = `-- name: AddMotivoDevolucao :exec
INSERT INTO motivo_devolucao (motivo) 
VALUES ($1)
`

func (q *Queries) AddMotivoDevolucao(ctx context.Context, motivo string) error {
	_, err := q.db.Exec(ctx, addMotivoDevolucao, motivo)
	return err
}

const buscaMotivoDevolucao = `-- name: BuscaMotivoDevolucao :one
SELECT id, motivo 
FROM motivo_devolucao 
WHERE id = $1 AND ativo = TRUE 
LIMIT 1
`

type BuscaMotivoDevolucaoRow struct {
	ID     int32
	Motivo string
}

func (q *Queries) BuscaMotivoDevolucao(ctx context.Context, id int32) (BuscaMotivoDevolucaoRow, error) {
	row := q.db.QueryRow(ctx, buscaMotivoDevolucao, id)
	var i BuscaMotivoDevolucaoRow
	err := row.Scan(&i.ID, &i.Motivo)
	return i, err
}

const buscaTodosMotivosDevolucao = `-- name: BuscaTodosMotivosDevolucao :many
SELECT id, motivo 
FROM motivo_devolucao 
WHERE ativo = TRUE
ORDER BY motivo ASC
`

type BuscaTodosMotivosDevolucaoRow struct {
	ID     int32
	Motivo string
}

func (q *Queries) BuscaTodosMotivosDevolucao(ctx context.Context) ([]BuscaTodosMotivosDevolucaoRow, error) {
	rows, err := q.db.Query(ctx, buscaTodosMotivosDevolucao)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscaTodosMotivosDevolucaoRow
	for rows.Next() {
		var i BuscaTodosMotivosDevolucaoRow
		if err := rows.Scan(&i.ID, &i.Motivo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMotivoDevolucao = `-- name: DeleteMotivoDevolucao :execrows
UPDATE motivo_devolucao
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeleteMotivoDevolucao(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMotivoDevolucao, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
