// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Tamanhos.sql

package repository

import (
	"context"
)

const addTamanho = `-- name: AddTamanho :exec
INSERT INTO tamanho (tamanho) 
VALUES ($1)
`

func (q *Queries) AddTamanho(ctx context.Context, tamanho string) error {
	_, err := q.db.Exec(ctx, addTamanho, tamanho)
	return err
}

const buscarTamanho = `-- name: BuscarTamanho :one
SELECT id, tamanho 
FROM tamanho 
WHERE id = $1 AND ativo = TRUE 
LIMIT 1
`

type BuscarTamanhoRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTamanho(ctx context.Context, id int32) (BuscarTamanhoRow, error) {
	row := q.db.QueryRow(ctx, buscarTamanho, id)
	var i BuscarTamanhoRow
	err := row.Scan(&i.ID, &i.Tamanho)
	return i, err
}

const buscarTamanhosPorIdEpi = `-- name: BuscarTamanhosPorIdEpi :many
SELECT t.id, t.tamanho
FROM tamanho t
INNER JOIN tamanhos_epis te ON t.id = te.IdTamanho
WHERE te.IdEpi = $1 AND te.ativo = TRUE
`

type BuscarTamanhosPorIdEpiRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTamanhosPorIdEpi(ctx context.Context, idepi int32) ([]BuscarTamanhosPorIdEpiRow, error) {
	rows, err := q.db.Query(ctx, buscarTamanhosPorIdEpi, idepi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTamanhosPorIdEpiRow
	for rows.Next() {
		var i BuscarTamanhosPorIdEpiRow
		if err := rows.Scan(&i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarTodosTamanhos = `-- name: BuscarTodosTamanhos :many
SELECT id, tamanho 
FROM tamanho 
WHERE ativo = TRUE
ORDER BY tamanho ASC
`

type BuscarTodosTamanhosRow struct {
	ID      int32
	Tamanho string
}

func (q *Queries) BuscarTodosTamanhos(ctx context.Context) ([]BuscarTodosTamanhosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosTamanhos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosTamanhosRow
	for rows.Next() {
		var i BuscarTodosTamanhosRow
		if err := rows.Scan(&i.ID, &i.Tamanho); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarTamanho = `-- name: DeletarTamanho :execrows
UPDATE tamanho
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarTamanho(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarTamanho, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEpiNosTamanhos = `-- name: UpdateEpiNosTamanhos :execrows
UPDATE tamanhos_epis
SET IdEpi = $2
WHERE IdEpi = $1 AND ativo = TRUE
`

type UpdateEpiNosTamanhosParams struct {
	Idepi   int32
	Idepi_2 int32
}

// Esta query atualiza a associação na tabela muitos-para-muitos
func (q *Queries) UpdateEpiNosTamanhos(ctx context.Context, arg UpdateEpiNosTamanhosParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEpiNosTamanhos, arg.Idepi, arg.Idepi_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
