// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: TipoProtecao.sql

package repository

import (
	"context"
)

const addProtecao = `-- name: AddProtecao :exec
INSERT INTO tipo_protecao (nome) 
VALUES ($1)
`

func (q *Queries) AddProtecao(ctx context.Context, nome string) error {
	_, err := q.db.Exec(ctx, addProtecao, nome)
	return err
}

const buscarProtecao = `-- name: BuscarProtecao :one
SELECT id, nome 
FROM tipo_protecao 
WHERE id = $1 AND ativo = TRUE 
LIMIT 1
`

type BuscarProtecaoRow struct {
	ID   int32
	Nome string
}

func (q *Queries) BuscarProtecao(ctx context.Context, id int32) (BuscarProtecaoRow, error) {
	row := q.db.QueryRow(ctx, buscarProtecao, id)
	var i BuscarProtecaoRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const buscarTodasProtecoes = `-- name: BuscarTodasProtecoes :many
SELECT id, nome 
FROM tipo_protecao 
WHERE ativo = TRUE
ORDER BY nome ASC
`

type BuscarTodasProtecoesRow struct {
	ID   int32
	Nome string
}

func (q *Queries) BuscarTodasProtecoes(ctx context.Context) ([]BuscarTodasProtecoesRow, error) {
	rows, err := q.db.Query(ctx, buscarTodasProtecoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodasProtecoesRow
	for rows.Next() {
		var i BuscarTodasProtecoesRow
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletarProtecao = `-- name: DeletarProtecao :execrows
UPDATE tipo_protecao
SET ativo = FALSE,
    deletado_em = NOW()
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarProtecao(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarProtecao, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProtecao = `-- name: UpdateProtecao :execrows
UPDATE tipo_protecao
SET nome = $2
WHERE id = $1 AND ativo = TRUE
`

type UpdateProtecaoParams struct {
	ID   int32
	Nome string
}

func (q *Queries) UpdateProtecao(ctx context.Context, arg UpdateProtecaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProtecao, arg.ID, arg.Nome)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
