// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Usuario.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarPorIdUsuario = `-- name: BuscarPorIdUsuario :one
SELECT id, nome, email, ativo
FROM usuarios
WHERE id = $1 AND ativo = TRUE
LIMIT 1
`

type BuscarPorIdUsuarioRow struct {
	ID    int32
	Nome  string
	Email string
	Ativo pgtype.Bool
}

func (q *Queries) BuscarPorIdUsuario(ctx context.Context, id int32) (BuscarPorIdUsuarioRow, error) {
	row := q.db.QueryRow(ctx, buscarPorIdUsuario, id)
	var i BuscarPorIdUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Ativo,
	)
	return i, err
}

const buscarTodosUsuarios = `-- name: BuscarTodosUsuarios :many
SELECT id, nome, email, ativo
FROM usuarios
WHERE ativo = TRUE
`

type BuscarTodosUsuariosRow struct {
	ID    int32
	Nome  string
	Email string
	Ativo pgtype.Bool
}

func (q *Queries) BuscarTodosUsuarios(ctx context.Context) ([]BuscarTodosUsuariosRow, error) {
	rows, err := q.db.Query(ctx, buscarTodosUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarTodosUsuariosRow
	for rows.Next() {
		var i BuscarTodosUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Ativo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id,nome, email, senha_hash
FROM usuarios
WHERE email = $1 AND ativo = TRUE
LIMIT 1
`

type BuscarUsuarioPorEmailRow struct {
	ID        int32
	Nome      string
	Email     string
	SenhaHash string
}

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
insert into usuarios (nome, email, senha_hash) values ($1, $2, $3)
`

type CreateUserParams struct {
	Nome      string
	Email     string
	SenhaHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Nome, arg.Email, arg.SenhaHash)
	return err
}

const deletarUsuario = `-- name: DeletarUsuario :execrows
UPDATE usuarios
SET ativo = FALSE
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) DeletarUsuario(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletarUsuario, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
