// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/davi-fernandesx/sistema-de-gestao-de-epi/model"
)

// EntregaInterface is an autogenerated mock type for the EntregaInterface type
type EntregaInterface struct {
	mock.Mock
}

// Addentrega provides a mock function with given fields: ctx, _a1
func (_m *EntregaInterface) Addentrega(ctx context.Context, _a1 model.EntregaParaInserir) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Addentrega")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EntregaParaInserir) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuscaEntrega provides a mock function with given fields: ctx, id
func (_m *EntregaInterface) BuscaEntrega(ctx context.Context, id int) (*model.EntregaDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscaEntrega")
	}

	var r0 *model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.EntregaDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.EntregaDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaEntregaCancelada provides a mock function with given fields: ctx, id
func (_m *EntregaInterface) BuscaEntregaCancelada(ctx context.Context, id int) (*model.EntregaDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscaEntregaCancelada")
	}

	var r0 *model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.EntregaDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.EntregaDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaEntregaPorIdFuncionario provides a mock function with given fields: ctx, idFuncionario
func (_m *EntregaInterface) BuscaEntregaPorIdFuncionario(ctx context.Context, idFuncionario int) ([]*model.EntregaDto, error) {
	ret := _m.Called(ctx, idFuncionario)

	if len(ret) == 0 {
		panic("no return value specified for BuscaEntregaPorIdFuncionario")
	}

	var r0 []*model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.EntregaDto, error)); ok {
		return rf(ctx, idFuncionario)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.EntregaDto); ok {
		r0 = rf(ctx, idFuncionario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, idFuncionario)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaEntregaPorIdFuncionarioCanceladas provides a mock function with given fields: ctx, idFuncionario
func (_m *EntregaInterface) BuscaEntregaPorIdFuncionarioCanceladas(ctx context.Context, idFuncionario int) ([]*model.EntregaDto, error) {
	ret := _m.Called(ctx, idFuncionario)

	if len(ret) == 0 {
		panic("no return value specified for BuscaEntregaPorIdFuncionarioCanceladas")
	}

	var r0 []*model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*model.EntregaDto, error)); ok {
		return rf(ctx, idFuncionario)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*model.EntregaDto); ok {
		r0 = rf(ctx, idFuncionario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, idFuncionario)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaTodasEntregas provides a mock function with given fields: ctx
func (_m *EntregaInterface) BuscaTodasEntregas(ctx context.Context) ([]*model.EntregaDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuscaTodasEntregas")
	}

	var r0 []*model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.EntregaDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.EntregaDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscaTodasEntregasCanceladas provides a mock function with given fields: ctx
func (_m *EntregaInterface) BuscaTodasEntregasCanceladas(ctx context.Context) ([]*model.EntregaDto, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuscaTodasEntregasCanceladas")
	}

	var r0 []*model.EntregaDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.EntregaDto, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.EntregaDto); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EntregaDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelarEntrega provides a mock function with given fields: ctx, id
func (_m *EntregaInterface) CancelarEntrega(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelarEntrega")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEntregaInterface creates a new instance of EntregaInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntregaInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntregaInterface {
	mock := &EntregaInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
