// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/davi-fernandesx/sistema-de-gestao-de-epi/model"
)

// EntradaRepository is an autogenerated mock type for the EntradaRepository type
type EntradaRepository struct {
	mock.Mock
}

// AddEntradaEpi provides a mock function with given fields: ctx, _a1
func (_m *EntradaRepository) AddEntradaEpi(ctx context.Context, _a1 *model.EntradaEpiInserir) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddEntradaEpi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.EntradaEpiInserir) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuscarEntrada provides a mock function with given fields: ctx, id
func (_m *EntradaRepository) BuscarEntrada(ctx context.Context, id int) (model.EntradaEpi, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarEntrada")
	}

	var r0 model.EntradaEpi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (model.EntradaEpi, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) model.EntradaEpi); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.EntradaEpi)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuscarTodasEntradas provides a mock function with given fields: ctx
func (_m *EntradaRepository) BuscarTodasEntradas(ctx context.Context) ([]model.EntradaEpi, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuscarTodasEntradas")
	}

	var r0 []model.EntradaEpi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.EntradaEpi, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.EntradaEpi); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.EntradaEpi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelarEntrada provides a mock function with given fields: ctx, id
func (_m *EntradaRepository) CancelarEntrada(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelarEntrada")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEntradaRepository creates a new instance of EntradaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntradaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntradaRepository {
	mock := &EntradaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
